language: elixir

otp_release:
  - 20.2
before_install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - set -e
  - MIX_ENV=test mix format --check-formatted
  - set +e
  - mix coveralls.json --umbrella
after_script:
  - bash <(curl -s https://codecov.io/bash)
  - bash .scripts/inch_report.sh

matrix:
  include:
  - elixir: "1.5.3"
    script:
      - mix coveralls.json --umbrella
  - elixir: "1.6.4"

notifications:
  email:
    recipients:
      - ananya95+travis@gmail.com
